CREATE TABLE IF NOT EXISTS login_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(128),
    email VARCHAR(320),
    ip_address INET,
    forwarded_ip INET,
    user_agent TEXT,
    login_status VARCHAR(32) NOT NULL,
    failure_reason TEXT,
    authentication_method VARCHAR(64),
    session_id UUID,
    token_id UUID,
    refresh_token_id UUID,
    device_id VARCHAR(256),
    device_name VARCHAR(256),
    device_type VARCHAR(64),
    browser VARCHAR(128),
    browser_version VARCHAR(64),
    operating_system VARCHAR(128),
    os_version VARCHAR(64),
    location VARCHAR(256),
    country_code VARCHAR(2),
    country_name VARCHAR(128),
    city VARCHAR(128),
    timezone VARCHAR(128),
    application VARCHAR(128),
    platform VARCHAR(128),
    api_version VARCHAR(64),
    suspicious BOOLEAN NOT NULL DEFAULT FALSE,
    risk_score INTEGER,
    mfa_required BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_successful BOOLEAN,
    mfa_method VARCHAR(64),
    mfa_at TIMESTAMPTZ,
    occurred_at TIMESTAMPTZ NOT NULL,
    login_at TIMESTAMPTZ,
    session_expires_at TIMESTAMPTZ,
    logout_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_login_audit_status CHECK (login_status IN (
        'SUCCESS', 'FAILED', 'LOCKED', 'MFA_REQUIRED', 'MFA_FAILED',
        'TOKEN_EXPIRED', 'ACCOUNT_DISABLED', 'ACCOUNT_NOT_FOUND'
    )),
    CONSTRAINT ck_login_audit_risk_score CHECK (risk_score IS NULL OR risk_score BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS idx_login_audit_user_time ON login_audit (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_status_time ON login_audit (login_status, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_username_time ON login_audit (username, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_email_time ON login_audit (email, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_session_id ON login_audit (session_id);
CREATE INDEX IF NOT EXISTS idx_login_audit_token_id ON login_audit (token_id);
CREATE INDEX IF NOT EXISTS idx_login_audit_ip_time ON login_audit (ip_address, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_forwarded_ip_time ON login_audit (forwarded_ip, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_login_audit_suspicious_time ON login_audit (suspicious, occurred_at DESC) WHERE suspicious;
CREATE INDEX IF NOT EXISTS idx_login_audit_risk_score ON login_audit (risk_score DESC) WHERE risk_score IS NOT NULL;

CREATE TABLE IF NOT EXISTS security_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_type VARCHAR(48) NOT NULL,
    event_status VARCHAR(24) NOT NULL,
    description TEXT,
    occurred_at TIMESTAMPTZ NOT NULL,
    ip_address INET,
    forwarded_ip INET,
    user_agent TEXT,
    device_id UUID,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ck_security_audit_event_type CHECK (event_type IN (
        'LOGIN', 'LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGIN_LOCKED', 'LOGIN_MFA_REQUIRED',
        'LOGIN_MFA_FAILED', 'LOGIN_TOKEN_EXPIRED', 'LOGIN_ACCOUNT_DISABLED', 'LOGIN_ACCOUNT_NOT_FOUND',
        'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_CHANGED', 'PASSWORD_RESET', 'PASSWORD_RESET_REQUESTED',
        'PASSWORD_RESET_COMPLETED', 'MFA_ENABLED', 'MFA_DISABLED', 'MFA_CHALLENGE',
        'MFA_CHALLENGE_FAILED', 'MFA_FAILED', 'ACCOUNT_LOCKED', 'ACCOUNT_UNLOCKED', 'ACCOUNT_DISABLED',
        'ACCOUNT_ENABLED', 'DEVICE_REGISTERED', 'NEW_DEVICE', 'DEVICE_REVOKED', 'DEVICE_TRUSTED',
        'DEVICE_UNTRUSTED', 'SESSION_CREATED', 'SESSION_REVOKED', 'SESSION_EXPIRED',
        'TOKEN_ISSUED', 'TOKEN_REFRESHED', 'TOKEN_REFRESH', 'TOKEN_EXPIRED', 'TOKEN_REVOKED',
        'TOKEN_REUSE_DETECTED', 'PERMISSION_DENIED', 'SUSPICIOUS_ACTIVITY',
        'SUSPICIOUS_LOGIN', 'CREDENTIALS_CHANGED', 'EMAIL_CHANGED', 'ROLE_CHANGED',
        'PERMISSION_CHANGED', 'PROFILE_CHANGED', 'OTHER'
    )),
    CONSTRAINT ck_security_audit_status CHECK (event_status IN ('SUCCESS', 'FAILURE', 'DENIED', 'DETECTED'))
);

CREATE INDEX IF NOT EXISTS idx_security_audit_user_time ON security_audit (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_event_time ON security_audit (event_type, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_status_time ON security_audit (event_status, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_device_time ON security_audit (device_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_ip_time ON security_audit (ip_address, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_forwarded_ip_time ON security_audit (forwarded_ip, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_audit_metadata ON security_audit USING GIN (metadata);

CREATE TABLE IF NOT EXISTS auth_device (
    id UUID PRIMARY KEY,
    user_id BIGINT,
    device_id UUID NOT NULL,
    display_name VARCHAR(128),
    device_type VARCHAR(64),
    platform VARCHAR(128),
    user_agent VARCHAR(1024),
    last_ip_address INET,
    trusted BOOLEAN NOT NULL DEFAULT FALSE,
    last_seen_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_auth_device_user_device UNIQUE (user_id, device_id)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_security_audit_device') THEN
        ALTER TABLE security_audit
            ADD CONSTRAINT fk_security_audit_device FOREIGN KEY (device_id)
            REFERENCES auth_device (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_auth_device_user_last_seen ON auth_device (user_id, last_seen_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_device_active_user ON auth_device (user_id) WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_device_last_ip ON auth_device (last_ip_address);

CREATE TABLE IF NOT EXISTS auth_session (
    session_id UUID PRIMARY KEY,
    user_id BIGINT,
    token_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    ip_address INET,
    CONSTRAINT uq_auth_session_token_id UNIQUE (token_id),
    CONSTRAINT ck_auth_session_expiry CHECK (expires_at > created_at)
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user_expiry ON auth_session (user_id, expires_at DESC);
CREATE INDEX IF NOT EXISTS idx_auth_session_active_user_expiry ON auth_session (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_auth_session_ip ON auth_session (ip_address);

DO $$
BEGIN
    IF to_regclass('tbl_users') IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_login_audit_user') THEN
            ALTER TABLE login_audit
                ADD CONSTRAINT fk_login_audit_user FOREIGN KEY (user_id)
                REFERENCES tbl_users (id) ON DELETE SET NULL;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_security_audit_user') THEN
            ALTER TABLE security_audit
                ADD CONSTRAINT fk_security_audit_user FOREIGN KEY (user_id)
                REFERENCES tbl_users (id) ON DELETE SET NULL;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_auth_device_user') THEN
            ALTER TABLE auth_device
                ADD CONSTRAINT fk_auth_device_user FOREIGN KEY (user_id)
                REFERENCES tbl_users (id) ON DELETE SET NULL;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_auth_session_user') THEN
            ALTER TABLE auth_session
                ADD CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id)
                REFERENCES tbl_users (id) ON DELETE SET NULL;
        END IF;
    END IF;
END $$;
