version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: auth_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db-init/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"
    hostname: postgres
    networks:
      - backend

  auth-service:
    build: ./AuthService
    depends_on:
      - postgres
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    networks:
      - backend

  attendance-service:
    build: ./AttendanceService
    depends_on:
      - postgres
    container_name: attendance-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    networks:
      - backend

  news-service:
    build: ./NewsService
    depends_on:
      - postgres
    container_name: news-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/news_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    networks:
      - backend

  gateway-service:
    build: "./GatewayOWSM"
    container_name: gateway-service
    ports:
      - "9001:9001"
    depends_on:
      - auth-service
      - attendance-service
      - news-service
      - postgres
    environment:
      SERVER_PORT: 9001
      SPRING_APPLICATION_NAME: GatewayOWSM

      SPRING_CLOUD_GATEWAY_ROUTES_0_ID: AuthService
      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:8081
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_0: Path=/api/users/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_1: Path=/api/roles/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_2: Path=/api/profile/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_3: Path=/api/auth/**
      SPRING_CLOUD_GATEWAY_ROUTES_0_PREDICATES_4: Path=/api/permissions/**

      SPRING_CLOUD_GATEWAY_ROUTES_1_ID: AttendanceService
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://attendance-service:8083
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_0: Path=/api/attendance/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_1: Path=/api/departments/**
      SPRING_CLOUD_GATEWAY_ROUTES_1_PREDICATES_2: Path=/api/offices/**

      SPRING_CLOUD_GATEWAY_ROUTES_2_ID: NewsService
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://news-service:8082
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_0: Path=/api/news/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_1: Path=/api/categories/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_2: Path=/api/comments/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_3: Path=/api/tags/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_4: Path=/api/authors/**
      SPRING_CLOUD_GATEWAY_ROUTES_2_PREDICATES_5: Path=/api/media-assets/**

      SPRING_CLOUD_GATEWAY_DEFAULT_FILTERS_0: DedupedResponseHeader=Access-Control-Allow-Origin RETAIN_UNIQUE
    restart: always
    networks:
      - backend

  frontend:
    build:
      context: ../FRONTEND/owsm-admin
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ../FRONTEND/owsm-admin:/app
      - /app/node_modules
    restart: always
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
