services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    hostname: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - backend

  postgres-init:
    image: postgres:15
    container_name: postgres-init

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGPASSWORD: 123

    command: >
      sh -c "
      psql -h postgres -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'auth_db'\" | grep -q 1 || psql -h postgres -U postgres -d postgres -c 'CREATE DATABASE auth_db';

      psql -h postgres -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'attendance_db'\" | grep -q 1 || psql -h postgres -U postgres -d postgres -c 'CREATE DATABASE attendance_db';

      psql -h postgres -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'news_db'\" | grep -q 1 || psql -h postgres -U postgres -d postgres -c 'CREATE DATABASE news_db';

      psql -h postgres -U postgres -d postgres -tc \"SELECT 1 FROM pg_database WHERE datname = 'gateway_db'\" | grep -q 1 || psql -h postgres -U postgres -d postgres -c 'CREATE DATABASE gateway_db';
      "

    restart: "no"

    networks:
      - backend

  auth-service:
    build:
      context: ./AuthService

    container_name: auth-service

    depends_on:
      postgres-init:
        condition: service_completed_successfully

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker

    restart: always

    networks:
      - backend

  attendance-service:
    build:
      context: ./attendanceService

    container_name: attendance-service

    depends_on:
      postgres-init:
        condition: service_completed_successfully

    ports:
      - "8083:8083"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker

    restart: always

    networks:
      - backend

  news-service:
    build:
      context: ./NewsService

    container_name: news-service

    depends_on:
      postgres-init:
        condition: service_completed_successfully

    ports:
      - "8082:8082"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/news_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_PROFILES_ACTIVE: docker

    restart: always

    networks:
      - backend

  gateway-service:
    build:
      context: ./GatewayOWSM
    container_name: gateway-service
    depends_on:
      - auth-service
      - attendance-service
      - news-service
    ports:
      - "9001:9001"
    environment:
      SERVER_PORT: 9001
      SPRING_APPLICATION_NAME: GatewayOWSM
      SPRING_PROFILES_ACTIVE: docker

      # This forces your specific configuration properties to override everything else directly
      SPRING_APPLICATION_JSON: '{
          "auth.service.uri": "http://auth-service:8081",
          "attendance.service.uri": "http://attendance-service:8083",
          "news.service.uri": "http://news-service:8082"
        }'
    restart: always
    networks:
      - backend

  frontend:
    build:
      context: ../FRONTEND/owsm-admin
      dockerfile: Dockerfile

    container_name: frontend

    depends_on:
      - gateway-service

    ports:
      - "3000:3000"

    command: npm run dev -- --host 0.0.0.0

    volumes:
      - ../FRONTEND/owsm-admin:/app

    restart: always

    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    driver: bridge